#include "gbc_components/instruction_set.h"

/// 8-Bit Immediate Loads

LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x06, B)
LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x0E, C)
LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x16, D)
LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x1E, E)
LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x26, H)
LOAD_IMMEDIATE_8_REGISTER_INSTRUCTION_DEFINITION(0x2E, L)
